#create regional climate forcing files from HNF data
#for area of single point run in Boise Basin Experimental Forest (BBEF) Southern Idaho

setwd("/glade/p/univ/uboi0003/CLM/WRFforc/d02/Precip")
precp_files<-list.files()
setwd("/glade/p/univ/uboi0003/CLM/WRFforc/d02/Solar")
rsds_files<-list.files()
setwd("/glade/p/univ/uboi0003/CLM/WRFforc/d02/TPQWL")
tas_files<-list.files()

library(RNetCDF)

#get coordinate data
domain<-open.nc("/glade/work/katiem/sfcdata/domain.lnd.ID_KM_singlept_c191104.nc")
lon<-var.get.nc(domain,"xc")
lat<-var.get.nc(domain,"yc")


for (i in precp_files){
  setwd("/glade/p/univ/uboi0003/CLM/WRFforc/d02/Precip")
  ncin<-open.nc(i)
  setwd("/glade/work/katiem/FATES_data/ID/singlept/WRF/Precip")
  ncout<-create.nc(paste("BBEF1pt_",i,sep="_"),clobber=T,prefill=F)
  dim.def.nc(ncout,"lon",1)
  dim.def.nc(ncout,"lat",1)
  dim.def.nc(ncout,"time",1,unlim=T)
  var.def.nc(ncout,"time","NC_DOUBLE",2)
  var.def.nc(ncout,"lon","NC_DOUBLE",0)
  var.def.nc(ncout,"lat","NC_DOUBLE",1)
  var.def.nc(ncout,"LATIXY","NC_DOUBLE",c(0,1))
  var.def.nc(ncout,"LONGXY","NC_DOUBLE",c(0,1))
  var.def.nc(ncout,"PRCP","NC_FLOAT",c(0,1,2))
  time<-var.get.nc(ncin,"time")
  dat<-var.get.nc(ncin,"PRCP")
  subdat<-array(NA,dim=c(1,1,length(time)))
  subdat[1,1,1:length(time)]<-dat[158,135,1:length(time)] 
  var.put.nc(ncout,"time",time)
  longxy <- array(NA,dim=c(1,1))
  latixy <- array(NA,dim=c(1,1))
  longxy[1,1] <- lon
  latixy[1,1] <- lat
  var.put.nc(ncout,"lon",lon)
  var.put.nc(ncout,"lat",lat)
  var.put.nc(ncout,"LONGXY",longxy)
  var.put.nc(ncout,"LATIXY",latixy)
  var.put.nc(ncout,"PRCP",subdat)
  att.copy.nc(ncin,"PRCP","units",ncout,"PRCP")
  att.put.nc(ncout,"PRCP","_FillValue","NC_DOUBLE",-9999.9)
  att.copy.nc(ncin, "PRCP", "description",ncout,"PRCP")
  att.put.nc(ncout,"PRCP","standard_name","NC_CHAR","Precipitation") 
  att.copy.nc(ncin,"time","units",ncout,"time")
  att.copy.nc(ncin,"time","calendar",ncout,"time")
  att.put.nc(ncout,"time","long_name","NC_CHAR","time") 
  att.put.nc(ncout,"lon","units","NC_CHAR","degrees_east") 
  att.put.nc(ncout,"lon","axis","NC_CHAR","X") 
  att.put.nc(ncout,"lon","long_name","NC_CHAR","longitude") 
  att.put.nc(ncout,"lat","units","NC_CHAR","degrees_north") 
  att.put.nc(ncout,"lat","axis","NC_CHAR","Y") 
  att.put.nc(ncout,"lat","long_name","NC_CHAR","latitude") 
  att.put.nc(ncout,"LATIXY","units","NC_CHAR","degrees_north") 
  att.put.nc(ncout,"LATIXY","long_name","NC_CHAR","latitude") 
  att.put.nc(ncout,"LONGXY","units","NC_CHAR","degrees_east") 
  att.put.nc(ncout,"LONGXY","long_name","NC_CHAR","longitude") 
  close.nc(ncout)
}

for (i in rsds_files){
  setwd("/glade/p/univ/uboi0003/CLM/WRFforc/d02/Solar")
  ncin<-open.nc(i)
  setwd("/glade/work/katiem/FATES_data/ID/singlept/WRF/Solar")
  ncout<-create.nc(paste("BBEF1pt_",i,sep="_"),clobber=T,prefill=F)
  dim.def.nc(ncout,"lon",1)
  dim.def.nc(ncout,"lat",1)
  dim.def.nc(ncout,"time",1,unlim=T)
  var.def.nc(ncout,"time","NC_DOUBLE",2)
  var.def.nc(ncout,"lon","NC_DOUBLE",0)
  var.def.nc(ncout,"lat","NC_DOUBLE",1)
  var.def.nc(ncout,"LATIXY","NC_DOUBLE",c(0,1))
  var.def.nc(ncout,"LONGXY","NC_DOUBLE",c(0,1))
  var.def.nc(ncout,"FSDS","NC_FLOAT",c(0,1,2))
  time<-var.get.nc(ncin,"time")
  dat<-var.get.nc(ncin,"FSDS")
  subdat<-array(NA,dim=c(1,1,length(time)))
  subdat[1,1,1:length(time)]<-dat[158,135,1:length(time)]
  var.put.nc(ncout,"time",time)
  longxy <- array(NA,dim=c(1,1))
  latixy <- array(NA,dim=c(1,1))
  longxy[1,1] <- lon
  latixy[1,1] <- lat
  var.put.nc(ncout,"lon",lon)
  var.put.nc(ncout,"lat",lat)
  var.put.nc(ncout,"LONGXY",longxy)
  var.put.nc(ncout,"LATIXY",latixy)
  var.put.nc(ncout,"FSDS",subdat)
  att.copy.nc(ncin,"FSDS","units",ncout,"FSDS")
  att.copy.nc(ncin,"FSDS","coordinates",ncout,"FSDS")
  att.put.nc(ncout,"FSDS","_FillValue","NC_DOUBLE",-9999.9)
  att.copy.nc(ncin,"FSDS","description",ncout,"FSDS")
  att.copy.nc(ncin,"time","units",ncout,"time")
  att.copy.nc(ncin,"time","calendar",ncout,"time")
  att.put.nc(ncout,"time","long_name","NC_CHAR","time")
  att.put.nc(ncout,"lon","units","NC_CHAR","degress_east")
  att.put.nc(ncout,"lon","axis","NC_CHAR","X")
  att.put.nc(ncout,"lon","long_name","NC_CHAR","longitude")
  att.put.nc(ncout,"lat","units","NC_CHAR","degrees_north")
  att.put.nc(ncout,"lat","axis","NC_CHAR","Y")
  att.put.nc(ncout,"lat","long_name","NC_CHAR","latitude")
  att.put.nc(ncout,"LATIXY","units","NC_CHAR","degrees_north")
  att.put.nc(ncout,"LATIXY","long_name","NC_CHAR","latitude")
  att.put.nc(ncout,"LONGXY","units","NC_CHAR","degrees_east")
  att.put.nc(ncout,"LONGXY","long_name","NC_CHAR","longitude")
  close.nc(ncout)
}

for (i in tas_files){
  setwd("/glade/p/univ/uboi0003/CLM/WRFforc/d02/TPQWL")
  ncin<-open.nc(i)
  setwd("/glade/work/katiem/FATES_data/ID/singlept/WRF/TPQWL")
  ncout<-create.nc(paste("BBEF1pt_",i,sep="_"),clobber=T,prefill=F)
  dim.def.nc(ncout,"lon",1)
  dim.def.nc(ncout,"lat",1)
  dim.def.nc(ncout,"time",1,unlim=T)
  var.def.nc(ncout,"time","NC_DOUBLE",2)
  var.def.nc(ncout,"lon","NC_DOUBLE",0)
  var.def.nc(ncout,"lat","NC_DOUBLE",1)
  var.def.nc(ncout,"LATIXY","NC_DOUBLE",c(0,1))
  var.def.nc(ncout,"LONGXY","NC_DOUBLE",c(0,1))
  var.def.nc(ncout,"WIND","NC_FLOAT",c(0,1,2))
  var.def.nc(ncout,"SHUM","NC_FLOAT",c(0,1,2))
  var.def.nc(ncout,"TBOT","NC_FLOAT",c(0,1,2))
  time<-var.get.nc(ncin,"time")
  dat<-var.get.nc(ncin,"WIND")
  subdat<-array(NA,dim=c(1,1,length(time)))
  subdat[1,1,1:length(time)]<-dat[158,135,1:length(time)]
  dat2<-var.get.nc(ncin,"SHUM")
  subdat2<-array(NA,dim=c(1,1,length(time)))
  subdat2[1,1,1:length(time)]<-dat2[158,135,1:length(time)]
  dat3<-var.get.nc(ncin,"TBOT")
  subdat3<-array(NA,dim=c(1,1,length(time)))
  subdat3[1,1,1:length(time)]<-dat3[158,135,1:length(time)]
  var.put.nc(ncout,"time",time)
  longxy <- array(NA,dim=c(1,1))
  latixy <- array(NA,dim=c(1,1))
  longxy[1,1] <- lon
  latixy[1,1] <- lat
  var.put.nc(ncout,"lon",lon)
  var.put.nc(ncout,"lat",lat)
  var.put.nc(ncout,"LONGXY",longxy)
  var.put.nc(ncout,"LATIXY",latixy)
  var.put.nc(ncout,"WIND",subdat)
  var.put.nc(ncout,"SHUM",subdat2)
  var.put.nc(ncout,"TBOT",subdat3)
  att.copy.nc(ncin,"WIND","units",ncout,"WIND")
  att.put.nc(ncout,"WIND","_FillValue","NC_DOUBLE",-9999.9)
  att.copy.nc(ncin,"WIND","description",ncout,"WIND")
  att.copy.nc(ncin,"TBOT","units",ncout,"TBOT")
  att.put.nc(ncout,"TBOT","_FillValue","NC_DOUBLE",-9999.9)
  att.copy.nc(ncin,"TBOT","description",ncout,"TBOT")
  att.copy.nc(ncin,"SHUM","units",ncout,"SHUM")
  att.put.nc(ncout,"SHUM","_FillValue","NC_DOUBLE",-9999.9)
  att.copy.nc(ncin,"SHUM","description",ncout,"SHUM")
  att.copy.nc(ncin,"time","units",ncout,"time")
  att.copy.nc(ncin,"time","calendar",ncout,"time")
  att.put.nc(ncout,"time","long_name","NC_CHAR","time")
  att.put.nc(ncout,"lon","units","NC_CHAR","degress_east")
  att.put.nc(ncout,"lon","axis","NC_CHAR","X")
  att.put.nc(ncout,"lon","long_name","NC_CHAR","longitude")
  att.put.nc(ncout,"lat","units","NC_CHAR","degrees_north")
  att.put.nc(ncout,"lat","axis","NC_CHAR","Y")
  att.put.nc(ncout,"lat","long_name","NC_CHAR","latitude")
  att.put.nc(ncout,"LATIXY","units","NC_CHAR","degrees_north")
  att.put.nc(ncout,"LATIXY","long_name","NC_CHAR","latitude")
  att.put.nc(ncout,"LONGXY","units","NC_CHAR","degrees_east")
  att.put.nc(ncout,"LONGXY","long_name","NC_CHAR","longitude")
  close.nc(ncout)
}
