#!/usr/bin/env bash

## When using WRF forcing data:
## copy over user_datm.streams.txt. (Precip, Solar, TPQW) to case dir
## confirm paths in two locations in user_datm.streams.txt
## and then submit


SRCDIR=/glade/work/katiem/git/ctsm
cd ${SRCDIR}
### CTSM git version
GITHASH1=`git log -n 1 --format=%h`

cd src/fates
### FATES git version
GITHASH2=`git log -n 1 --format=%h`

### no fire runs
CASE=junk_FATES_SPR_TEST002

SETUP_CASE=${CASE}_0.125x0.125

PARAM_FILE=param_file_Pinus_Pond_190930.nc


##PARAM_DIR=${SRCDIR}/src/fates/parameter_files/
PARAM_DIR=/glade/work/katiem/FATES_data/parameter_files/

CASE_NAME=${SETUP_CASE}_${GITHASH1}_${GITHASH2}

casedir=/glade/work/katiem/FATES_cases/Idaho/

basedir=$SRCDIR/cime/scripts/

cime_model=cesm
MACH=cheyenne

## compset to set up global case
COMP=2000_DATM%GSWP3v1_CLM50%FATES_SICE_SOCN_RTM_SGLC_SWAV

## resolution to set up global case
RES=ne120_t12

## project numbers
PROJECT=UBOI0003

#### load_machine_files
cd $basedir

./create_newcase --case ${casedir}${CASE_NAME} --res ${RES} --compset ${COMP} --project ${PROJECT} --run-unsupported --mach ${MACH}


cd ${casedir}${CASE_NAME}

export CLM_DOMAIN_DIR=/glade/work/katiem/sfcdata
export CLM_SURFDAT_DIR=/glade/work/katiem/sfcdata

export SITE_NAME=Idaho_BBEF
export CLM_USRDAT_DOMAIN=domain.lnd.0.125x0.125_tx0.1v2.140704_BBEF.nc
export CLM_USRDAT_SURDAT=surfdata_0.125x0.125_hist_16pfts_Irrig_CMIP6_simyr2005_c190613_BBEF.nc


##modify env_mach_pes file
./xmlchange NTASKS_ATM=-1
./xmlchange NTASKS_CPL=-1
./xmlchange NTASKS_GLC=-1
./xmlchange NTASKS_OCN=-1
./xmlchange NTASKS_WAV=-1
./xmlchange NTASKS_ICE=-1
./xmlchange NTASKS_LND=-1
./xmlchange NTASKS_ROF=-1
./xmlchange NTASKS_ESP=-1

./case.setup
./preview_namelists
##modify env_run
