#!/bin/bash

#SBATCH --time=8:00:00
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH -p leaf
#SBATCH --mem-per-cpu=100G
#SBATCH -J "WRF_CLM_PRECIP"
#SBATCH --mail-user=katiemurenbeeld@u.boisestate.edu
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL

#Load modules and run wrf_to_clm.py subsetting script

module load python/intel/3.5
python wrf_to_clm_precip.py
